### ISSUE TITLE
:Android:createPdf FAILED

### ISSUE THREAD

**Issue by AndreasAusD** [vogellacompany/com.vogella.tutorials.android#8]
Hallo,

ich versuche ein PDF zu erstellen, bekomme aber eine Fehlermeldung.

>java -version
>java version "1.8.0_111"
>Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
>Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
>
>git clone https://github.com/vogellacompany/com.vogella.tutorials.android.git
>cd com.vogella.tutorials.android/ 
>./gradlew cP

>ubuntu@ubuntu:~/com.vogella.tutorials.android$ ./gradlew cP --stacktrace
>:Android:createPdf
>(Errno::ENOENT) /home/ubuntu/com.vogella.tutorials.android/themes/basic-theme.yml
>:Android:createPdf FAILED
>
>FAILURE: Build failed with an exception.

Stacktrace siehe Anhang...
[stacktrace.txt](https://github.com/vogellacompany/com.vogella.tutorials.android/files/664038/stacktrace.txt)

MfG
A.Hoppe

**Comment by fap-** [comment]
For a quick fix you can get the `basic-theme.yml` from here: https://github.com/vogellacompany/com.vogella.tutorials.eclipse/blob/master/themes/basic-theme.yml
Just put it under `/home/ubuntu/com.vogella.tutorials.android/themes/`

I'll add it to the repository later.
